"""
FastAPI Backend for Crystal Agent - Streaming Chat Interface

This backend provides Server-Sent Events (SSE) streaming for real-time AI responses.
Designed for commercial-grade chat experience with Gemini AI.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Optional, AsyncGenerator
import json
import sys
import os
import asyncio
from pathlib import Path

# Add parent directory to path to import utils
sys.path.append(str(Path(__file__).parent.parent))

from utils.ai_brain import AIBrain
from utils.text_analyzer import TextAnalyzer
from utils.local_storage import LocalStorage
from utils.context_engine import ContextEngine
from config.settings import Settings

# Initialize FastAPI app
app = FastAPI(
    title="Crystal Agent API",
    description="Commercial-grade streaming chat API",
    version="1.0.0"
)

# CORS middleware for local development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify exact origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount static files
static_path = Path(__file__).parent.parent / "frontend" / "static"
templates_path = Path(__file__).parent.parent / "frontend" / "templates"

if static_path.exists():
    app.mount("/static", StaticFiles(directory=str(static_path)), name="static")

# Initialize modules
ai_brain = AIBrain(Settings.GEMINI_API_KEY, Settings.AI_MODEL) if Settings.GEMINI_API_KEY else None
text_analyzer = TextAnalyzer()
local_storage = LocalStorage()
context_engine = ContextEngine(local_storage)

# ==================== Conversation History Buffer ====================
# In-memory conversation history (use Redis/DB in production)
conversation_history = {}  # {user_id: [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}]}
MAX_HISTORY_TURNS = 5  # Keep last 5 conversation turns (5 user + 5 assistant = 10 messages)


def add_to_history(user_id: str, role: str, content: str):
    """Add a message to conversation history"""
    if user_id not in conversation_history:
        conversation_history[user_id] = []

    conversation_history[user_id].append({
        "role": role,
        "content": content
    })

    # Keep only the last MAX_HISTORY_TURNS * 2 messages
    if len(conversation_history[user_id]) > MAX_HISTORY_TURNS * 2:
        conversation_history[user_id] = conversation_history[user_id][-(MAX_HISTORY_TURNS * 2):]


def get_history(user_id: str) -> list:
    """Get conversation history for a user"""
    return conversation_history.get(user_id, [])


# ==================== Request/Response Models ====================

class ChatMessage(BaseModel):
    """Chat message request model"""
    message: str
    user_id: Optional[str] = "default_user"


class ChatResponse(BaseModel):
    """Chat response model"""
    response: str
    type: str
    emotion: str
    amount: Optional[float] = None


# ==================== Streaming Helper Functions ====================

async def stream_gemini_response(
    user_message: str,
    context: dict
) -> AsyncGenerator[str, None]:
    """
    Stream AI response from Gemini in real-time.

    This function yields chunks of text as they are generated by Gemini,
    enabling a typewriter effect on the frontend.

    Args:
        user_message: User's input message
        context: Context dict with user profile, recent logs, etc.

    Yields:
        JSON strings containing text chunks in SSE format
    """
    if not ai_brain:
        # Fallback for demo mode
        demo_response = "Hello! This is a demo response. The AI is not configured yet."
        for char in demo_response:
            yield f"data: {json.dumps({'chunk': char, 'done': False})}\n\n"
            await asyncio.sleep(0.02)  # Simulate typing speed
        yield f"data: {json.dumps({'chunk': '', 'done': True})}\n\n"
        return

    try:
        # Use Gemini's streaming capability
        import google.generativeai as genai

        # Build the prompt with context
        prompt = ai_brain._build_prompt(user_message, context)

        # Get streaming response from Gemini
        model = genai.GenerativeModel(Settings.AI_MODEL)
        response = model.generate_content(prompt, stream=True)

        # Stream each chunk as it arrives
        for chunk in response:
            if chunk.text:
                # Send chunk in SSE format
                yield f"data: {json.dumps({'chunk': chunk.text, 'done': False})}\n\n"

        # Send completion signal
        yield f"data: {json.dumps({'chunk': '', 'done': True})}\n\n"

    except Exception as e:
        # Send error in SSE format
        error_msg = f"Error generating response: {str(e)}"
        yield f"data: {json.dumps({'error': error_msg, 'done': True})}\n\n"


# ==================== API Endpoints ====================

@app.get("/", response_class=HTMLResponse)
async def read_root():
    """Serve the main chat interface"""
    html_file = templates_path / "index.html"

    if html_file.exists():
        return HTMLResponse(content=html_file.read_text(), status_code=200)
    else:
        return HTMLResponse(
            content="<h1>Crystal Agent Streaming Chat</h1><p>Template not found. Please check frontend/templates/index.html</p>",
            status_code=404
        )


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "ai_configured": ai_brain is not None,
        "version": "1.0.0"
    }


@app.post("/api/chat")
async def chat(message: ChatMessage) -> ChatResponse:
    """
    Standard chat endpoint (non-streaming).
    Use /api/chat/stream for real-time streaming.
    """
    # Analyze the message
    analysis = text_analyzer.analyze(message.message)
    detected_type = analysis.get('type', '日記')
    detected_emotion = analysis.get('emotion', '普通')
    detected_amount = analysis.get('amount')

    # Get context
    context = {}
    profile = local_storage.get_user_profile()
    if profile:
        context['profile'] = profile

    ai_context = context_engine.get_context_for_ai(message.message, context.get('profile'))
    context.update(ai_context)

    # Add conversation history to context
    history = get_history(message.user_id)
    if history:
        context['conversation_history'] = history

    # Generate response
    if ai_brain:
        response_text = ai_brain.generate_response(message.message, context)
    else:
        response_text = "AI not configured. Please set GEMINI_API_KEY in .env file."

    # Save to conversation history
    add_to_history(message.user_id, "user", message.message)
    if response_text:
        add_to_history(message.user_id, "assistant", response_text)

    # Save to local storage
    local_storage.add_life_log(
        content=message.message,
        type_=detected_type,
        amount=detected_amount,
        emotion=detected_emotion
    )

    return ChatResponse(
        response=response_text,
        type=detected_type,
        emotion=detected_emotion,
        amount=detected_amount
    )


@app.post("/api/chat/stream")
async def chat_stream(message: ChatMessage):
    """
    Streaming chat endpoint using Server-Sent Events (SSE).

    This endpoint streams AI responses in real-time, enabling a typewriter effect
    and ChatGPT-like experience on the frontend.

    Response format (SSE):
        data: {"chunk": "text", "done": false}
        data: {"chunk": "", "done": true}
    """
    import asyncio

    # Analyze the message
    analysis = text_analyzer.analyze(message.message)
    detected_type = analysis.get('type', '日記')
    detected_emotion = analysis.get('emotion', '普通')
    detected_amount = analysis.get('amount')

    # Send metadata first
    async def generate():
        # Send metadata
        metadata = {
            'type': 'metadata',
            'detected_type': detected_type,
            'detected_emotion': detected_emotion,
            'detected_amount': detected_amount
        }
        yield f"data: {json.dumps(metadata)}\n\n"

        # Get context
        context = {}
        profile = local_storage.get_user_profile()
        if profile:
            context['profile'] = profile

        ai_context = context_engine.get_context_for_ai(message.message, context.get('profile'))
        context.update(ai_context)

        # Add conversation history to context
        history = get_history(message.user_id)
        if history:
            context['conversation_history'] = history

        # Collect full response for history
        full_ai_response = ""

        # Stream the response
        async for chunk_data in stream_gemini_response(message.message, context):
            # Extract chunk text from SSE format
            if chunk_data.startswith("data: "):
                chunk_json = json.loads(chunk_data[6:])
                if chunk_json.get('chunk') and not chunk_json.get('done'):
                    full_ai_response += chunk_json['chunk']

            yield chunk_data

        # Save user message to conversation history
        add_to_history(message.user_id, "user", message.message)

        # Save AI response to conversation history
        if full_ai_response:
            add_to_history(message.user_id, "assistant", full_ai_response)

        # Save to local storage after streaming completes
        # (In production, this should be non-blocking)
        local_storage.add_life_log(
            content=message.message,
            type_=detected_type,
            amount=detected_amount,
            emotion=detected_emotion
        )

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"  # Disable nginx buffering
        }
    )


@app.get("/api/stats")
async def get_stats():
    """Get user statistics"""
    stats = local_storage.get_stats()
    return stats


@app.get("/api/logs")
async def get_logs(limit: int = 10):
    """Get recent logs"""
    logs = local_storage.get_recent_logs(limit=limit)
    return {"logs": logs}


# ==================== Run Server ====================

if __name__ == "__main__":
    import uvicorn

    print("\n" + "="*60)
    print("🚀 Crystal Agent - Streaming Chat Server")
    print("="*60)
    print(f"Server: http://localhost:8000")
    print(f"API Docs: http://localhost:8000/docs")
    print(f"AI Status: {'✅ Configured' if ai_brain else '⚠️ Not configured'}")
    print("="*60 + "\n")

    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )
